CREATE DATABASE quickpost CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE quickpost;

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

